### ISSUE TITLE
DEV To-do list  July

### ISSUE THREAD

**Issue by csolievna** [ideesculture/newport#14]
- [x] editing an object opened through a search: problem with attributes. DONE
- [x] search on non existing objects: "requested keys of a value that is not an object (search.js l174) DONE
- [ ] new objects not indexed? they can't be found inside Providence, even if they DO exist in the base
- [x] creating an object: glitch on the type selection screen DONE
- [x] creating several new objects one after another: bug risk DONE
- [ ] support LIST's attribute type
- [ ] support embedded attributes (for example, dimensions: width, height, depth)
- [ ] send medias to the server
- [ ] images do not appear when objects are shown in a mosaic on first upload. they appear if you reload the page
- [ ] some objects are unclickable
- [ ] edit.js l506 undefined is not an object (but attributes are correctly saved... strange). This error does not fire in tishadow
- [ ] if data is not sent to the server, it is kept in the data table. The timer launching an attempt to send these left datas regularly is missing
- [x] pop-up windows for relations
- [ ] login procedure
- [x] add option "keep on editing this object" when saving new object
- [ ] change the look of the thing (ugly) IN PROCESS
- [x] egg timer functionnality is broken
- [x] localisations (storage locations)
- [ ] ca_objects_edit model: function updating the local db when changes are made by the user
- [ ] "remove" button seems to not work (bundle line when editing an object)

**Comment by csolievna** [comment]
search on non existing objects: DONE

**Comment by csolievna** [comment]
editing an object opened through a search: DONE. The bug was due to attribute selection by object type.

**Comment by csolievna** [comment]
glitch when creating an object: DONE.

**Comment by csolievna** [comment]
bug risk when creating new objects: DONE. You now have multiple choices when your object was saved: go back to main page or create another new object. It would be nice to add a choice "keep on editing this object", but time is running.

**Comment by csolievna** [comment]
Last modified objects work, but the cache is a problem here. 
However, it brings back the correct objects and generates the list of 3 parents dynamically when the software is freshly compiled.

![capture d ecran 2015-07-22 a 10 49 01](https://cloud.githubusercontent.com/assets/3668519/8821699/fc9aec32-305f-11e5-81fe-af0bd2ba19b6.png)

**Comment by csolievna** [comment]
research on entities. 
![capture d ecran 2015-07-22 a 14 52 03](https://cloud.githubusercontent.com/assets/3668519/8825708/66dded30-3081-11e5-88b8-2836bc4e898c.png)

**Comment by csolievna** [comment]
![capture d ecran 2015-07-28 a 14 47 18](https://cloud.githubusercontent.com/assets/3668519/8931581/a69b42a0-3537-11e5-99a8-fad02d470292.png)
![capture d ecran 2015-07-28 a 14 47 27](https://cloud.githubusercontent.com/assets/3668519/8931582/a69bff1a-3537-11e5-9510-39d8fa08196e.png)
![capture d ecran 2015-07-28 a 14 47 33](https://cloud.githubusercontent.com/assets/3668519/8931584/a6a7a202-3537-11e5-8977-86d7bdb478bb.png)
![capture d ecran 2015-07-28 a 14 47 43](https://cloud.githubusercontent.com/assets/3668519/8931583/a6a0f434-3537-11e5-8b20-6a603899ab3e.png)

**Comment by csolievna** [comment]
**Captures of pop-up window (modal) for entity creation**
Missing: 
- choose relation type
- more fields in entity pop-up window

![capture d ecran 2015-07-29 a 17 09 05](https://cloud.githubusercontent.com/assets/3668519/8961355/142b36c6-3615-11e5-8912-9085f976249f.png)
![capture d ecran 2015-07-29 a 17 09 34](https://cloud.githubusercontent.com/assets/3668519/8961356/14305b74-3615-11e5-8a6e-a119e5fcaf09.png)
![capture d ecran 2015-07-29 a 17 09 47](https://cloud.githubusercontent.com/assets/3668519/8961353/142488f8-3615-11e5-921a-aaf9681003dc.png)
![capture d ecran 2015-07-29 a 17 10 49](https://cloud.githubusercontent.com/assets/3668519/8961354/1429a55e-3615-11e5-9729-810f4d0b2b65.png)
